print(61*"=")
print("    Program Hitung Jumlah Kata dan Karakter Dengan Python")
print(61*"=")
input_kata = input('masukkan teks: ')
x = input_kata.split()
print('Jumlah Kata: ',(len(x)))
print('Jumlah Karakter: ',len(input_kata))
print('Jika dibalik akan menampilkan kata: ',''.join(reversed(input_kata)))
print(61*"=")
